### ISSUE TITLE
[NAVBAR] Add SDGs to Topic Navbar dropdown

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/Takwimu#404] opened 2018-09-26 09:07 UTC
**Is your feature request related to a problem? Please describe.**
Add a topic navbar dropdown and accompanying SDGs.

**Describe the solution you'd like**
![screenshot_2018-09-26_12-01-53](https://user-images.githubusercontent.com/6592749/46069566-7c4c0200-c184-11e8-8ea1-0a0bb4416b8e.png)

Web: https://zpl.io/beYER7P
App: zpl://screen?pid=5b1a4192c1a8233544fcc66a&sid=5b438c2bfe428cd85f09f1c8

**Describe alternatives you've considered**
Currently implementation is just a nav-link

**Additional context**
Relate to #70, #294

**Comment by DavidLemayian** [comment] 2018-09-26 14:37
Duplicate of #292

**Closed by DavidLemayian** 2018-09-26 14:37 UTC
Labels: duplicate
