### ISSUE TITLE
Support Service Page Form Submit button not implemented

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#263] opened 2018-07-26 08:19 UTC
**Describe the bug**
I go here https://dev.takwimu.africa/about/support-services and click the 'submit enquiry' form button and nothing happens

**To Reproduce**
go to https://dev.takwimu.africa/about/support-services and click the 'submit enquiry' form button

**Expected behavior**
I should see some acknowledgement that my enquiry has been submitted - meanwhile the message should get sent to zendesk

**Screenshots**
![takwimu02](https://user-images.githubusercontent.com/14904333/43250270-ddc2a274-90b4-11e8-897b-fbddc7dd8893.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by phillipahereza** [comment] 2018-07-26 09:42
@kilemensi lemme take a stab at this

**Comment by phillipahereza** [comment] 2018-07-26 09:56
@kilemensi this issue is related to #265 I guess should we first wait for the redesign from Zaang based on issues raised in #265 or do a rough implementation of what's suggested in the issue like removing the checkboxes for what issue you're interested in?

**Comment by kilemensi** [comment] 2018-07-26 10:18
I was thinking lets get the back-end sorted for the current design (sending it to zendesk) while we wait for the redesign from Zaang @phillipahereza. This will at least help us close #120 which Mtuchi had started.

**Comment by DavidLemayian** [comment] 2018-07-26 11:08
Duplicate of #265

**Closed by DavidLemayian** 2018-07-26 11:08 UTC
