### ISSUE TITLE
Enable Ordering of Takwimu Services

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#249] opened 2018-07-23 18:47 UTC
We need to be able to order how Site Services appear in the UI.
![screen_shot_2018-07-23_at_19_45_20_png_and_screen_shot_2018-07-23_at_13_30_31_png_and_desktop](https://user-images.githubusercontent.com/14904333/43096481-273fe12e-8eb1-11e8-804c-b4bff76c568c.png)

**Comment by DavidLemayian** [comment] 2018-07-23 18:52
Duplicate of #247

**Closed by DavidLemayian** 2018-07-23 18:52 UTC
